--EXEC DBMS_STATS.GATHER_SCHEMA_STATS(NULL, CASCADE => TRUE)
ALTER SYSTEM FLUSH BUFFER_CACHE;
ALTER SYSTEM FLUSH BUFFER_POOL;

SET AUTOTRACE ON
--SELECT TITRE FROM FILM WHERE ID_FILM = 50273;

--SELECT titre FROM film WHERE annee = 1999;

-- SELECT titre FROM film
-- WHERE annee=1999 OR titre='La piscine';

SELECT COUNT(*) FROM film WHERE id_film BETWEEN 50273 AND 60000;

SELECT COUNT(*) FROM FILM WHERE annee=1999;