all:
	javac Client.java Mandelbrot.java Task.java Point.java
	java Client

2:
	javac Client.java Mandelbrot.java Task.java Point.java
	java Client &
	java Client &

5:
	javac Client.java Mandelbrot.java Task.java Point.java
	java Client &
	java Client &
	java Client &
	java Client &
	java Client &

10:
	javac Client.java Mandelbrot.java Task.java Point.java
	java Client &
	java Client &
	java Client &
	java Client &
	java Client &
	java Client &
	java Client &
	java Client &
	java Client &
	java Client &
#./clients.sh

clean:
	rm *.class
