DELETE roles;
DELETE film;
DELETE acteur;

INSERT INTO film
SELECT
    LEVEL,
    CONCAT(DBMS_RANDOM.STRING('u', 1), DBMS_RANDOM.STRING('l', DBMS_RANDOM.value(5, 10))),
    FLOOR(DBMS_RANDOM.VALUE(1990, 2022))
FROM DUAL CONNECT BY LEVEL <= 10000;

INSERT INTO acteur
SELECT
    LEVEL,
    DBMS_RANDOM.String('u', DBMS_RANDOM.value(4, 12))
FROM DUAL CONNECT BY LEVEL <= 10000;

INSERT INTO roles
SELECT 
    id_film, id_acteur
FROM film, acteur
WHERE id_acteur BETWEEN 250 AND 500
AND id_film BETWEEN 1 AND 250
AND NOT EXISTS (SELECT * FROM roles r WHERE r.id_film = id_film AND r.id_acteur=id_acteur);