DROP Table R2;
CREATE TABLE R2(
    i INTEGER,
    j INTEGER,
    k INTEGER,
    PRIMARY KEY(i)
);
INSERT INTO R2 VALUES (3, 3, 3);
INSERT INTO R2 VALUES (2, 2, 2);
INSERT INTO R2 VALUES (5, 5, 5);
INSERT INTO R2 VALUES (1, 1, 1);
INSERT INTO R2 VALUES (4, 4, 4);
INSERT INTO R2 VALUES (8, 8, 8);
INSERT INTO R2 VALUES (7, 7, 7);
INSERT INTO R2 VALUES (9, 9, 9);
INSERT INTO R2 VALUES (6, 9, 6);