DROP TABLE T;
CREATE Table T (
    i INTEGER,
    a CHAR(2000),
    b CHAR(2000),
    c CHAR(2000),
    d CHAR(2000),
    e CHAR(2000),
    PRIMARY KEY (i)
);

INSERT INTO T(i) VALUES(1);
INSERT INTO T(i) VALUES(2);
INSERT INTO T(i) VALUES(3);