SET TIMING OFF;
ALTER SYSTEM FLUSH BUFFER_CACHE;
ALTER SYSTEM FLUSH SHARED_POOL;

--EXEC DBMS_STATS.GATHER_SCHEMA_STATS(NULL, CASCADE => TRUE)
SET AUTOTRACE ON EXPLAIN STATISTICS;
SET AUTOTRACE TRACEONLY;
SET TIMING ON;

-- SELECT TITRE FROM FILM WHERE ID_FILM = 50273;

-- SELECT titre FROM film WHERE annee = 1999;

-- SELECT titre FROM film
-- WHERE annee=1999 OR titre='La piscine';

-- SELECT COUNT(*) FROM film WHERE id_film BETWEEN 50273 AND 60000;

-- SELECT COUNT(*) FROM FILM WHERE annee=1999;

-- SELECT ANNEE, COUNT(TITRE) FROM FILM GROUP BY ANNEE;

-- SELECT titre, id_acteur
-- FROM FILM, ROLES
-- WHERE FILM.id_film=ROLES.id_film;
 
SELECT DISTINCT id_acteur FROM ACTEUR;

-- SELECT titre, COUNT(nom)
-- FROM ROLES, FILM, ACTEUR
-- WHERE FILM.id_film=ROLES.id_film AND ROLES.id_acteur=ACTEUR.id_acteur
-- AND FILM.id_film BETWEEN 3054 AND 8013
-- GROUP BY titre;
-- Utilisation de conseils

--SELECT /*+Full FILM*/
--TITRE FROM FILM WHERE ID_FILM = 50273;